---
title: "Welcome to Introduction to Bayesian Statistics (STAT 446/646)"
author: "AG Schissler"
date: "25 Jan 2021 (*updated: `r Sys.Date()`)*"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(scales)
library(tidyverse)
```

## I. Start-of-class work

Let's discuss:

## What are the major goals of statistical inference?

## Frequentist approach to statistics

- parameters, the numerical characteristics of a population (think of them as **targets of learning**), are fixed but unknown constants.
- probabilities as *always* long-run relative frequency.
- Statistical procedures are judged how often things occur in an infinite number of repetitions of the experiment
 
## Bayesian approach to statistics

- We model parameters as random variables since we are uncertain about their true value.
- The basic rules of probability are used **directly** to make statistical inferences about the parameters (it's how we **update** our beliefs about uncertain quantities in light of data)
- Probability statements must be interpreted as a "degree of belief" (not hypothetical long-run relative frequency)
- Each person can have his/her own prior beliefs before (and must be able to formalize that belief as a probability distribution)

## II. Getting to know our community

Please introduce yourself (briefly) to the class by telling us:

1) Name (what you liked to be called)
2) Major
3) Professional goals
4) A hobby or interest you have.

### Instructor: A. Grant Schissler, PhD

- teaching experience: 6 years of high schools teaching, >6 years at higher Ed teaching
- education: BS in Applied Math, MS in Applied Stat, PhD in Statistics
- research interests: Developing stats methods for personalized medicine, statistical computing, Bayesian modeling, clustering, high-dimensional data, large scale hypothesis testing, simulation, multivariate analysis, limited data analyses
- other interests: being a dog dad, reading, hiking, tennis, running, video games

### Reciprocal interview

#### Questions for you:

1) What are your goals for the course?  
2) What is your best outcome imagined for the course?  
3) What is your worst outcome imagined for the course?  
4) What is the most likely outcome imagined for the course (prediction)?  
5) What can I do to help you learn best?

#### Questions for me?

Please, please, ask anything on your mind (about the class) --- anxieties, hopes, policies, procedures, anything.

### Take away

Assume good will among everyone here. **Ask Questions** and **Work Together** --- these are the most important reasons for class time.

## III. Course expectations and learning outcomes

### Course goals and caveats

#### Audience

- This course is designed for a broad audience: Grad, UG, various majors.
- My goal introduce Bayesian statistics through building an active-learning community (us).
- Classes are designed to engage and require you to think, let passively sit and absorb.

#### Scope

- The course follows Bolstad & Curran closely.  
- You are expected to know basic probability, algebra, calculus, and linear algebra.
- The first chapters are treated quickly, with hopes of addressing the later, more advanced topics.
- You will have to perform some symbolic manipulation (basic proof writing).
- Programming is required for applied Bayesian Statistics. This should not be your first programming experience.
- We will use `R` and `rmarkdown` with $\LaTeX$ embedded to complete problem sets.
- Extensive derivations may be submitted by scanned handwriting but this is discouraged in general.

#### Not happy? Talk with me

- Ff I'm ever not meeting your learning goals or other issue, just talk with me.
- It saddens me to see evaluations at the end that indicate problems I could have helped had I known.
- It doesn't help you or me to keep issues to yourself.

### Estimated time commitment

- Class participation: 2.5 hours/week.  
- Readings: 2 hours/week.  
- Problem Sets: 2.5 hours/week.  
- Midterms: 3 hours total (1 hour x 3 exams)  
- Final Exam: 6 hours total (6 hours x 1 exam)  

$(5, 10)$ hours a week is a reasonable interval for weekly hours.

Let me know if you are spending much more time than this.

### Syllabus

Let me open up `RStudio` and render the syllabus.

1. Alone. Please read the syllabus and list/mark 5 most important things.
2. Together. Share with the whole group.

### Detailed learning outcomes

[learning outcomes](https://github.com/grizant/Intro_Bayes_Course/blob/develop/course_materials/Intro-to-Bayesian-Statistics_learning_outcomes.pdf)

You can always ask, "How does this activity relate to the learning outcomes?". 

### Course resources

#### Canvas (WebCampus)

- Course announcements
- Official assignments and due dates
- Gradebook management
- Secure file submissions
- Secure file sharing
- Preferred way to message the instructor

#### Mastering `R` and `RStudio`

https://education.rstudio.com/learn/beginner/

https://education.rstudio.com/learn/intermediate/

https://education.rstudio.com/learn/expert/

#### Term project

646 students are required to complete a term project with my guidance. More on this soon.

#### Github

Just clone and enjoy. Note that files will be updated from the previous semester as we go. So it would not be wise to go too far ahead. Once a file is uploaded to Canvas, clone the repo again. Sorry no forks.

[https://github.com/grizant/Intro_Bayes_Course/tree/develop](https://github.com/grizant/Intro_Bayes_Course/tree/develop)

## V. Closing . 3-2-1

- 3 next actions you need to take
- 2 things you learned
- 1 thing you are looking forward to in the class.

Share with the class.
