---
title: "BAYESIAN INFERENCE FOR MULTIVARIATE NORMAL MEAN VECTOR"
subtitle: "Chapter 18"
author: "AG Schissler"
date: "19 Apr 2021 (*updated: `r Sys.Date()`)*"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(printr)
library(Bolstad)
set.seed(04192021)
## xaringan::inf_mr('./22_ch18_MVN.Rmd')
```

# i. Admin & Startup

## Week 13 of 16 Focus

- Read Ch.18
- Receive and act on Midterm 3 & HW 10 Ch.17 C1, C3 feedback
- Practice on HW 11 Ch.18 1-3, due Friday Apr 23.
- READING DAY Wednesday Apr 21 NO CLASS

## Today's plan

- Prime by discussion via HW 11, Ch.18 1-3 exercise prompts.
- Discuss Ch.18
- Summarize, Revisit HW or Q & A

*Please contribute questions and comments*

# I. Preview HW 11, Ch.18, 1-3

## Preview HW 11, Ch.18, 1-3

This HW is about following prescribed steps and understanding/communicating. 

- Ch.18.1: Importing the data should be easy. I recommend to factorize `Part`, e.g. `bottle.df$Part <- factor(bottle.df$Part)`.
- Ch.18.2: Repeats some code, no need to duplicate plots. Write a short description of what you see. 
- Ch.18.3: Report values as you go so that I can check your work (such as the sample mean vector for Bottle #5 and the test statistics X0). Interpret the results in context (not mentioned in the problem stated, but part of the HW rubric).

# II. Discuss Ch. 18 with examples

## Discuss Ch. 18 with examples

- etext p.393
- Overview, big ideas
- Powerful modeling strategy
- Matrix notation 

## 18.1 Bivariate Normal

- Begin with 2D bivariate normal model
- Properties and techniques for verifying/computing marginals

## 18.2 Multivariate Normal

- Matrix form for dimension $k \geq 2$. Thing of beauty.
- Subsets also MVN

## 18.3 Posterior distribution of the MVN when $\Sigma$ is known

- Single observation
- Random sample
- Updating formula for MVN

## 18.4 Credible region of the MVN when $\Sigma$ is known

- p.401 equation called a *Wald interval*, quadratic form gives chi-squared distribution
- Testing point hypothesis using credible region (topic in HW Ch.18 C3).

## 18.5 MVN with unknown $\Sigma$

- The Inverse Wishart Distribution (higher dimensional analog of inverse-chi-squared).
- Inv-Wishart is a prob distribution on the space of symmetric positive definite matrices.
- Covariances are (semi-)positive definiteness matrices. Highly structured with lots of useful properties/theory.
- Likelihood derivation (18.8).
- Finding the exact posterior when the joint conj. prior is used for all parameters.

# Closing (5 min)

- Summary
- HW discussion
- other?
