---
title: "FINAL EXAM POSTER SESSION"
subtitle: "STAT 446"
author: "AG Schissler"
date: "3 May 2021 (*updated: `r Sys.Date()`)*"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r LoadLib, echo = FALSE, eval = TRUE, message=FALSE, warning=FALSE, results = "hide"}
set.seed( 05032021 )
library(tidyverse)
library(printr)
## xaringan::inf_mr('25_posterSession.Rmd')
## str(knitr::opts_chunk$get())
```

<!-- open up etext as you go. don't typeset the chapter -->

# i. Week 15 Focus

- Students receive and act on all HW feedback.
- Students apply Bayesian methods to real world data (Final Exam/Poster).
- Students present their preliminary Final Exam poster.

## Today's plan

i. Students present their preliminary Final Exam poster.

*Please contribute questions and comments*

# Poster presentations

## Organization

- The purpose is to discuss the projects and get feedback in time to make adjustments.
- No one is judging or grading you. This is supposed to be fun and educational.
- I will give you a participation grade for showing up prepared.
- To organize, I'll randomly select students to present for a few minutes. Take turns sharing/discussing your work.
- I'll bring everyone back together for general comments and closing.

## Summary and closing

- General feedback.
 
## Closing

- Thank you for a great semester!
- I hope you feel confident that you can correctly apply/communicate the techniques from Bolstad and Curran.
- I also hope that see the power of a Bayesian approach to statistics.
- It would mean a lot to me if you complete an evaluation at [www.unr.edu/evaluate](www.unr.edu/evaluate). Please remember that my job depends on student feedback. I appreciate your time to thoughfully complete the survey and provide honest ratings. I'd love to hear what I did well as well as how I can get better (please be kind when you do this).
- Best wishes for your future.
