---
title: "STAT 646 Virtual Poster Session"
author: "AG Schissler"
date: "5/04/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Start-of-class work:

- I'll start this virtual poster session with some introductory comments and guidance to everyone.  
- Then we'll begin the project discussion and evaluations in *breakout rooms*.  
- Please critically discuss the project with the poster presenters. 
- Make sure you spend time at each poster.
- Please be polite and actually engage/learn.

## Project titles and teams

### Predicting NBA Player Scores Using Bayesian Statistics

*Austin Boone*

### Robust Bayesian Prior Methodology for Risk Assessment

*Bo Liu and Jessica Logan*

### Bayesian Multilevel Modeling to Detect Partisan Lean

*Benjamin Agyare, Jaucelyn Canfield, and Conner Dayton*

### How Economic Prosperity Impacts Crime Rate in Las Vegas

*Jacob Ellis*

### Evaluating Fire Emissions Inventories for Modeling Smoke Transport in the Sierra Nevada Mountains Using Bayesian Statistics

*Samantha Faulstich*

### Comparison of Existing scRNA-seq Imputation Methods

*Tyler Ewing and Richard Foote*

## Closing: 3-2-1

Non-project students: Please vote for your favorite projects using the Zoom poll after you have visited everyone to receive your 10 bonus points.

