---
title: "STAT 446/646: Introduction to Bayesian Statistics"
semester: "Spring 2021"
instructor: 'Alfred "Grant" Schissler, Ph.D.'
left_col:
  - field: "Email"
    value: "aschissler@unr.edu"
  - field: "Office Phone"
    value: "(775) 784-4661"
  - field: "Office Location"
    value: "DMS 224"
  - field: "Office Hours"
    value: "TBD"
  
right_col:
  - field: "Web"
    value: "<a href='https://www.grantschissler.com'>www.grantschissler.com</a>"
  - field: "Class Location"
    value: "Online (Zoom)"
  - field: "Class Hours"
    value: "MoWe 1:00pm to 2:15pm"
output: 
  html_document:
    css: style.css
    template: template.html
    self_contained: true
    toc: true
    toc_depth: 1
---

```{r setup, include=FALSE}
library(tidyverse)
mon <- as.Date("2021-01-25")
# fri <- as.Date("2016-01-08")
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 return(tmp)
}
```

## Course Description

This course introduces Bayesian statistics to a technical audience. Early on, we focus on the logic behind Bayesian statistics, including the mathematical formalization of updating beliefs under uncertainty. Then we describe Bayesian methods for well-known probability models and compare these methods to classical (frequentist) alternatives. Topics include Bayes' Theorem, prior specification, Bayesian inference for discrete and continuous univariate random variables, and linear regression. We'll implement methods analytically and using software such as Minitab, `R`, and `Stan`.

*Instructor's role*

- Help explain and guide student understanding and skill development.
- Organize the course structure and assignments.
- Lead weekly class discussions.
- Evaluate student work and provide feedback.

*Student's role*

- Complete the readings before the week's discussion meeting.
- Submit completed assignments on time.
- Participate in discussions. 
- Prepare for and complete course exams.
- Conduct and report on a research project (646).

## Catalog Description

Statistical inference using Bayes' Theorem. Topics include posterior analysis for continuous and discrete random variables, prior specification, Bayesian regression, multivariate inference, and posterior sampling through Markov Chain Monte Carlo.

## Course Prerequisites

STAT 352 or STAT 467/667 or with instructor approval. STAT 445/645 is a suggested preparation.

## Student Learning Outcomes

Upon successful completion of the course, students will be able to 

* demonstrate understanding of the concepts that underlie Bayesian inference and compare the results to frequentist alternatives.
* conduct Bayesian inference analytically and interpret the results.
* perfom Bayesian analyses using professional statistical packages (`R` and `Stan`).

In addition to the above 400-level outcomes, graduate students will be able to 

* synthesize course concepts in an application of Bayesian modeling to real-world data.

## Textbooks & Course Materials

*Introduction to Bayesian Statistics*, 3rd edition, by William M. BOLSTAD and James M. CURRAN.

[Textbook website](https://www.wiley.com/en-us/Introduction+to+Bayesian+Statistics%2C+3rd+Edition-p-9781118091562)

**MAKE SURE TO GET THE 3rd EDITION**

*Supplemental texts*

Modern best practices for coding and reporting `R` analyses:  
*R for data science: import, tidy, transform, visualize, and model data*, Hadley WICKHAM and Garrett GROLEMUND.
[Online textbook](https://r4ds.had.co.nz/)

Excellent Introduction to applied Bayesian modeling motivated by information theory:
*Statistical Rethinking*, 2nd edition, Richard MCELREATH
[Textbook website](https://xcelab.net/rm/statistical-rethinking/)

Standard Bayesian reference textbook:  
*Bayesian Data Analysis*, 3rd edition by Andrew GELMAN et al.
[Textbook website](http://www.stat.columbia.edu/~gelman/book/)

*Mastering `R` and `RStudio`*

https://education.rstudio.com/learn/beginner/

https://education.rstudio.com/learn/intermediate/

https://education.rstudio.com/learn/expert/

## WebCampus/Canvas

WebCampus/Canvas will be used for the majority of class business. Students are responsible for monitoring Announcements, Assignments/Due Dates, Course Files, and the Gradebook. The preferred mode of commuication for course-related discussion with the instructor is through Canvas messaging.

https://unr.instructure.com/login/canvas

# Attendance

Students are expected to attend class.
If important circumstances prevent this, it is the student's responsibility to find out what was covered in class, what was assigned for reading or homework, and what special announcements (if any) were made.
"Excessive absence" in this class will be construed to be absence from more than 10 percent of the scheduled class sessions, whether excused or unexcused.

# Assignments

## Problem sets

Problem sets will be assigned each week, due on Fridays. You are encouraged to discuss assignments between each other and with instructor. However, the assignment must be completed and submitted individually. 

## Midterms
There will be three online-based midterm examinations. The first due Friday, 26 Feb 2021, the second due Friday, 19 Mar 2021, and the third Friday, 9 April 2021.

## Final exam
There will be a take-home final exam, due Friday, 7 May 2021. 

## Exam policy

Exams will be released roughly a week to before the due date. You must complete the exams without help. See Canvas for more details on take-home examination procedures.

## Makeup, Late Policy

* Completed problem sets exams are due on Fridays.
* Late assignments/exams will be given a 20% penalty per business day received late. (i.e., Saturday -0%, Sunday -0%, Monday -20% , Tuesday -40%, ..., Friday -100%).
* Exceptions will be made when a student misses work due to a documented (doctor's note) illness or an extraordinary situation (up to the discretion of the instructor). 
* There will be no early or make-up exams. 
* If you need to miss an exam due to participation in a religious holiday or an official university activities (including athletics and other sanctioned activities), please make arrangements with the instructor at least two weeks prior to the exam in question. 

**I'll drop (trim) your 2 lowest grades in the "Problem Set" category to protect against 1-2 outlying points having too much weight (e.g., a 0).**

# Grading

The course has a weighted grading scheme. There are three categories of assignments for 446 students. Table 1 shows the percentages for each category and the number of assignments (n). Table 2 gives the similar table for 646 students with the addition of a "Project" category. Table 3 displays the percentage thresholds determining the final overall letter grade.

| Assignment | n  | %  |
|------------|----|----|
| Problem set  | 14 | 55 |
| Midterm    | 3  | 30 |
| Final Exam | 1  | 15 |
Table: Table 1. 446 grading scheme.

| Assignment | n  | %  |
|------------|----|----|
| Problem set  | 14 | 50 |
| Midterm    | 3  | 15 |
| Final Exam | 1  | 15 |
| Project | 1  | 20 |
Table: Table 2. 646 grading scheme.

| Letter grade | % Range      |
|--------------|--------------|
| A            | 89.9 - up    |
| A-            | 87.9 - 89.8    |
| B+            | 84.9 - 87.8  |
| B            | 79.9 - 84.8  |
| B-            | 77.9 - 79.8  |
| C+            | 74.9 - 77.8  |
| C            | 69.9 - 74.8  |
| C-            | 67.9 - 69.8  |
| D            | 59.9 - 67.8  |
| F            | below - 59.8 |
Table: Table 3. Percentage range to letter grade conversion. 

*The instructor reserves the right to deviate from Table 3.*

# Additional statements

## Diversity Statement

The University of Nevada, Reno is committed to providing a safe learning and work environment for all. If you believe you have experienced discrimination, sexual harassment, sexual assault, domestic/dating violence, or stalking, whether on or off campus, or need information related to immigration concerns, please contact the University’s Equal Opportunity & Title IX Office at (775) 784-1547. Resources and interim measures are available to assist you. For more information, please visit [http:www.unr.edu/equal-opportunity-title-ix](http:www.unr.edu/equal-opportunity-title-ix).

## Disability Statement
Any student with a disability needing academic adjustments or accommodations is requested to speak with the [http:www.unr.edu/drc](Disability Resource Center) as soon as possible to arrange for appropriate accommodations.

## Academic Conduct
Please be professional. Prepare for and engage in class. Be on time and submit timely work. Please visit [http:www.unr.edu/student-conduct](http:www.unr.edu/student-conduct) for our official student code of conduct.

## Academic Success Services
Your student fees cover usage of the University Math Center, University Tutoring Center, and University Writing Center. These centers support your classroom learning; it is your responsibility to take advantage of their services. Keep in mind that seeking help outside of class is the sign of a responsible and successful student.

## University Recording Policy
Surreptitious or covert videotaping of class or unauthorized audio recording of class is prohibited by law and by Board of Regents policy. This class may be videotaped or audio recorded only with the written permission of the instructor. In order to accommodate students with disabilities, some students may have been given permission to record class lectures and discussions. Therefore, students should understand that their comments during class may be recorded.

## Academic Dishonesty
Cheating, plagiarism, or otherwise obtaining grades under false pretenses constitutes academic dishonesty according to the code of this university. Academic dishonesty will not be tolerated and penalties can include canceling a student’s enrollment without a grade or giving an F for the assignment or for the entire course. See the University Academic Standards policy: [UAM 6,502](https://www.unr.edu/administrative-manual/6000-6999-curricula-teaching-research/instruction-research-procedures/6502-academic-standards).

## Statement on content accessibility:

This course may leverage 3rd party web/multimedia content, if you experience any issues accessing this content, please notify your instructor.

## Statement on COVID-19 Training Policies

Students must complete and follow all guidelines as stated in the Student COVID-19 Training modules, or any other trainings or directives provided by the University.

## Statement on COVID-19 Face Coverings:

In response to COVID-19, and in alignment with State of Nevada Governor Executive Orders, Roadmap to Recovery for Nevada plans, Nevada System of Higher Education directives, the University of Nevada President directives, and local, state, and national health official guidelines face coverings are required at all times while on campus, except when alone in a private office. This includes the classroom, laboratory, studio, creative space, or any type of in-person instructional activity, and public spaces.

A “face covering” is defined as a “covering that fully covers a person’s nose and mouth, including without limitation, cloth face mask, surgical mask, towels, scarves, and bandanas” (State of Nevada Emergency Directive 024).

Students that cannot wear a face covering due to a medical condition or disability, or who are unable to remove a mask without assistance may seek an accommodation through the Disability Resource Center.

## Statement on COVID-19 Social Distancing:

Face coverings are not a substitute for social distancing. Students shall observe current social distancing guidelines where possible in accordance with the Phase we are in while in the classroom, laboratory, studio, creative space (hereafter referred to as instructional space) setting and in public spaces. Students should avoid congregating around instructional space entrances before or after class sessions. If the instructional space has designated entrance and exit doors students are required to use them. Students should exit the instructional space immediately after the end of instruction to help ensure social distancing and allow for the persons attending the next scheduled class session to enter.

## Statement on COVID-19 Disinfecting Your Learning Space:

Disinfecting supplies are provided for you to disinfect your learning space. You may also use your own disinfecting supplies.

## Statement on COVID-19, COVID-19 Like Symptoms, and Contact with Someone Testing Positive for COVID-19:

Students must conduct daily health checks in accordance with CDC guidelines. Students testing positive for COVID 19, exhibiting COVID 19 symptoms or who have been in direct contact with someone testing positive for COVID 19 will not be allowed to attend in-person instructional activities and must leave the venue immediately. Students should contact the Student Health Center or their health care provider to receive care and who can provide the latest direction on quarantine and self-isolation. Contact your instructor immediately to make instructional and learning arrangements.

## Statement on Failure to Comply with Policy (including as outlined in this Syllabus) or Directives of a University Employee

In accordance with section 6,502 of the University Administrative Manual, a student may receive academic and disciplinary sanctions for failure to comply with policy, including this syllabus, for failure to comply with the directions of a University Official, for disruptive behavior in the classroom, or any other prohibited action. “Disruptive behavior" is defined in part as behavior, including but not limited to failure to follow course, laboratory or safety rules, or endangering the health of others. A student may be dropped from class at any time for misconduct or disruptive behavior in the classroom upon recommendation of the instructor and with approval of the college dean. A student may also receive disciplinary sanctions through the Office of Student Conduct for misconduct or disruptive behavior, including endangering the health of others, in the classroom. The student shall not receive a refund for course fees or tuition.

# Tentative course schedule

Students please study the materials before the assigned class session.
Class readings and assignments are subject to change, contingent on mitigating circumstances and the progress we make as a class.

<div class="week">`r advdate(mon, 1)`: Organization & Intro to Bayes </div>

- Readings: Bolstad Ch. 1 - 3.
- Practice: Please complete Problem Set 1 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Welcome to 4/646! We'll discuss the structure of the course and expectations for students/instructor.  
*Wednesday topic*: Ch.1-3 Statistics and Data Science review.

<div class="week">`r advdate(mon, 2)`: Ch. 4 Plausible reasoning/Probability/Bayes' Rule </div>

- Readings: Bolstad Ch. 4.
- Practice: Please complete Problem Set 2 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Ch. 4 Deductive logic vs plausible reasoning. Bayes rule.   
*Wednesday topic*: Ch. 4 Bayes rule , Bayes factor, odds

<div class="week">`r advdate(mon, 3)`: Ch. 5 Discrete random variables </div>

- Readings: Bolstad Ch. 5.
- Practice: Please complete Problem Set 3 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Ch. 5 Discrete random variables  
*Wednesday topic*: Ch. 5 Discrete random variables

<div class="week">`r advdate(mon, 4)`: Ch. 6 Bayesian inference for discrete RVs </div>

- Readings: Bolstad Ch. 6.
- Practice: Please complete Problem Set 4 and submit in Canvas by the end of the week.
- Exams: Midterm 1 released.
- Notes: None.

*Monday topic*: President's Day. No class.  
*Wednesday topic*: Ch. 6 Bayesian inference for discrete RVs

<div class="week">`r advdate(mon, 5)`: Ch. 7-8 Continuous RVs and Bayesian inference for binomial proportion $\pi$ </div>

- Readings: Bolstad Ch. 7-8.
- Practice: Please complete Problem Set 5 and submit in Canvas by the end of the week.
- Exams: Midterm 1 due Friday 26 Feb 2021.
- Notes: None.

*Monday topic*: Ch. 7 Continuous RVs  
*Wednesday topic*: Ch. 8 Bayes inference for binomial proportion $\pi$

<div class="week">`r advdate(mon, 6)`:  Ch. 9 Comparing Bayes/Frequentist for $\pi$ </div>

- Readings: Bolstad Ch. 9
- Practice: Please complete Problem Set 6 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: Drop Day is 3 Mar 2021.

*Monday topic*: Ch. 9 Comparing Bayes/Frequentist for estimating $\pi$   
*Wednesday topic*: Ch. 9 Comparing Bayes/Frequentist for testing $\pi$

<div class="week">`r advdate(mon, 7)`:  Ch. 10 Bayesian inference for Poisson mean  </div>

- Readings: Bolstad Ch. 10
- Practice: Please complete Problem Set 7 and submit in Canvas by the end of the week.
- Exams: Midterm 2 released.
- Notes: None.

*Monday topic*: Ch. 10 Bayes inference for Poisson mean.  
*Wednesday topic*: Reading Day. No class.

<div class="week">`r advdate(mon, 8)`:  Ch. 11-12 Bayesian inference for normal mean $\mu$  </div>

- Readings: Bolstad Ch. 11-12
- Practice: Please complete Problem Set 8 and submit in Canvas by the end of the week.
- Exams: Midterm 2 due Friday 12 March 2021.
- Notes: None.

*Monday topic*: Ch. 11 Bayes inference for normal mean $\mu$  
*Wednesday topic*: Ch. 12 Comparing Bayes/Frequentist inference for $\mu$

<div class="week">`r advdate(mon, 9)`:  Ch. 13 Bayesian inference for difference between normal means  </div>

- Readings: Bolstad Ch. 13
- Practice: Please complete Problem Set 9 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Ch. 13 Bayes inference for diff in normal mean  
*Wednesday topic*: No Instruction Day. No class.

<div class="week">`r advdate(mon, 10)`:  Ch. 14 Bayesian inference for simple linear regression  </div>

- Readings: Bolstad Ch. 14
- Practice: Please complete Problem Set 10 and submit in Canvas by the end of the week.
- Exams: Midterm 3 released.
- Notes: None.

*Monday topic*: Ch. 14 Bayesian inference for simple linear regression  
*Wednesday topic*: Ch. 14 Bayesian inference for simple linear regression

<div class="week">`r advdate(mon, 11)`:  Ch. 15-16 Bayesian inference for standard deviation, Robust methods  </div>

- Readings: Bolstad Ch. 15-16
- Practice: Please complete Problem Set 11 and submit in Canvas by the end of the week.
- Exams: Midterm 3 due Friday 9 Apr 2021.
- Notes: None.

*Monday topic*: Ch. 15 Bayes for $\sigma$  
*Wednesday topic*: Ch. 16 Robust Bayes via mixture modeling

<div class="week">`r advdate(mon, 12)`:  Ch. 17 Bayesian inference unknown mean/variance </div>

- Readings: Bolstad Ch. 17.
- Practice: Please complete Problem Set 12 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Ch. 17 Bayesian inference unknown mean/variance  
*Wednesday topic*: Ch. 17 Bayesian inference unknown mean/variance

<div class="week">`r advdate(mon, 13)`:  Ch. 18 Bayesian inference multivariate normal mean vector </div>

- Readings: Bolstad Ch. 18.
- Practice: Please complete Problem Set 13 and submit in Canvas by the end of the week.
- Exams: None.
- Notes: None.

*Monday topic*: Ch. 18 Bayesian inference multivariate normal mean vector  
*Wednesday topic*: Reading Day. No class.

<div class="week">`r advdate(mon, 14)`:  Ch. 19 Bayesian inference multiple linear regression </div>

- Readings: Bolstad Ch. 19.
- Practice: Please complete Problem Set 14 and submit in Canvas by the end of the week.
- Exams: Final exam released.
- Notes: Matrix (linear) algebra required.

*Monday topic*: Ch. 19 Bayesian inference multiple linear regression  
*Wednesday topic*: Ch. 19 Bayesian inference multiple linear regression

<div class="week">`r advdate(mon, 14)`:  Ch. 20 Introduction to Computational Bayes </div>

- Readings: Bolstad Ch. 20.
- Practice: None.
- Exams: Final exam due Friday 7 May 2021.
- Notes: None.

*Monday topic*: Ch. 20 Computational Bayes including Markov Chain Monte Carlo (MCMC).  
*Wednesday topic*: Prep Day. No class.

